on: [push, pull_request, issues]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["node"]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install
